### ISSUE TITLE
It seems parsing "open ap "via iwlist inappropriately (which doesn't have password)

### ISSUE THREAD

**Issue by ipodipad** [Datamart/iwlscan#1]
open ap doesn't have "security" field. ( IE: )
Therefore, parsing goes wrong.

**Comment by vpodk** [comment]
Thank you for your comment.
Fixed in commit 610ad795bac266fa66f924d86309ef1cb3bb4e71

**Comment by ipodipad** [comment]
Thanks for quick patching for this issue.
However, I saw iwlist cannot parse WEP security and seems it displays as "UNKNOWN : blahblah..".
How do you can handle this?

**Comment by krailo** [comment]
Thank you for your question.
The tool follows the rule:
- if "Encryption key:on", and
- if security is not defined or "Unknown: xxx..."
- then it's a WEP.

Please see [test-output-iwlist.txt](https://github.com/Datamart/iwlscan/blob/master/test-output-iwlist.txt) as an example of iwlist output.
